config/routes.rb
Rails.application.routes.draw do
  resources :business_settings do
    get 'activate_ride_requests', to: 'business_settings#activate_ride_requests', as: 'activate_ride_requests'
    get 'deactivate_ride_requests', to: 'business_settings#deactivate_ride_requests', as: 'deactivate_ride_requests'
    get 'on_off_tracker', to: 'business_settings#on_off_tracker', as: 'on_off_tracker'
  end
  resources :kill_switches
  devise_for :users do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'ride_requests/inactive', to:'ride_requests#inactive', as: 'inactive'
  get 'ride_requests/new_2', to:'ride_requests#new_2', as: 'new_2'

  resources :ride_requests do
    get '/assign/:shuttle_id', to: 'ride_requests#assign_to_shuttle', as: 'assign_shuttle'
    get '/mark_clear', to: 'ride_requests#mark_clear', as: 'mark_clear'
    get 'advance_status', to:'ride_requests#advance_status', as: 'advance_status'
    get 'reset_status', to:'ride_requests#reset_status', as: 'reset_status'
    get 'send_inital_sms', to: 'ride_requests#send_inital_sms', as: 'send_inital_sms'
    get :autocomplete_pickup_location_name, :on => :collection

  end
  get 'ride_request/manager', to: "ride_requests#manager", as:'ride_request_manager'
  get 'ride_request/report', to: "ride_requests#report", as:'ride_request_report'
  get 'ride_request/show_all', to: "ride_requests#show_all", as:'ride_requests_show_all'
  get 'ride_request/check_last_ride/:id', to: "ride_requests#check_last_ride", as:'last_ride'
  resources :shuttle_stops
  resources :shuttles do
    get 'set_looping', to: 'shuttles#set_looping', as:'set_looping'
    get 'stop_looping', to: 'shuttles#stop_looping', as:'stop_looping'
    get 'set_active', to: 'shuttles#set_active', as:'set_active'
    get 'set_inactive', to: 'shuttles#set_inactive', as:'set_inactive'
    get 'driver', to: "shuttles#driver", as: "driver"
    get 'clear_all', to: "shuttles#clear_all", as: "clear_all"
    get 'all_rolling', to: "shuttles#all_rolling", as: "all_rolling"
    get 'check_last_ride/:id', to: 'shuttles#check_last_ride', as: 'check_last_ride'
    get 'check_hash/:hash', to: 'shuttles#check_hash', as: 'check_driver_hash'
  end
  get 'shuttle_locations', to: 'shuttles#shuttle_locations', as: 'shuttle_locations'
  get 'shuttle/trackers', to: 'shuttles#trackers', as: 'shuttle_trackers'
  get 'driver', to:'shuttles#driver', as: 'driver'
  get 'driver/:id', to:'shuttles#driver', as: 'driver_id'
  post 'driver/:id/set_location', to:'shuttles#set_location', as: 'set_location'
  post 'ride_requests/rider/set_location', to:'ride_requests#set_rider_location', as: 'set_rider_location'
  post 'ride_requests/rider/set_rider_info', to:'ride_requests#set_rider_info', as: 'set_rider_info'
  get 'ride_requests/rider/clear_session', to: 'ride_requests#clear_rider_info', as: 'clear_rider_info'
  get 'assign_drivers', to: 'shuttles#assign_drivers', as: 'assign_drivers'
  resources :images
  resources :experience_occurances do
    resources :reservations
  end
  resources :reservations do
    get 'deposit', to: 'reservations#deposit', as: 'deposit'
  end
  get 'my_reservations', to:'reservations#my_reservations', as: 'my_reservations'

  get 'experiences/featured', to: 'experiences#featured'
  resources :experiences do
    get 'add_company/:id', to: 'experiences#add_company', as: 'add_company'
    get 'remove_company/:id', to: 'experiences#remove_company', as: 'remove_company'
    resources :reservations
    resources :images
  end

  resources :experience_ideas
  resources :businesses
  resources :locations do
    get 'show_after_2', to: 'locations#set_show_after_2', as: 'show_after_2'
    get 'toggle_shuttle_stop', to: 'locations#toggle_shuttle_stop', as: 'toggle_shuttle_stop'
  end
  resources :categories

  resources :charges
  get 'set_play_sound', to: "business_settings#set_play_sound", as: 'set_play_sound'

  get 'test_text', to: 'twilios#send_test', as: 'twilio_test'

  get 'right_column_list', to: 'pages#right_column_list', as: 'right_column_list'
  get 'front_desk', to: 'pages#front_desk', as: 'front_desk'
  post 'pages/front_desk/send_sms', to: 'pages#send_sms', as: 'pages_send_sms'
  post 'pages/front_desk/send_sms_intl', to: 'pages#send_sms_intl', as: 'pages_send_sms_intl'
  get 'message_sent', to: 'pages#text_message_sent', as: 'text_message_sent'

  get 'mobile_pages/ride_request', to: 'mobile_pages#ride_request', as: 'mobile_ride_request'
  post 'mobile_pages/create', to: 'mobile_pages#create', as: 'mobile_create_ride_request'
  get 'mobile_pages/ride_request_details/:ride_request_id', to: 'mobile_pages#ride_request_details', as: 'mobile_ride_request_details'
  root "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  layout 'locations_2'
  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :location_id, :category_id, :contact_name, :contact_phone, :website, :description, :logo, :email)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_with(model: business, local: true, class: 'form inputs-underline') do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :business_name %>
  </div>
  <% locations = [] %>
  <% locations << ["-- Please Select --", "-- Please Select --"]%>
  <% Location.all.each do |l|  %>
  <% locations << [l.name, l.id] %>
  <% end %>

  <div class="field">
    <%= form.label :location_id %>
    <%= form.select(:location_id, options_for_select(locations), {}, { :class => 'ride-select', style: 'max-width:100%'}) %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id, id: :business_category_id %>
  </div>

  <div class="field">
    <%= form.label :contact_name %>
    <%= form.text_field :contact_name, id: :business_contact_name %>
  </div>

  <div class="field">
    <%= form.label :contact_phone %>
    <%= form.text_field :contact_phone, id: :business_contact_phone %>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :business_email %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, id: :business_website %>
  </div>
  <div class="field">
    <%= form.label :logo %>
    <%= form.file_field :logo, id: :business_logo,  class: 'form-control' %>
  </div>
    <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :business_description, rows: 8, class: 'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Save",  class: 'btn btn-primary pull-right'  %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function () {
    $('.ride-select').select2();
  });
</script>

app/views/businesses/edit.html.erb
<div class='container'>
<h1>Editing Business</h1>

    <%= render 'form', business: @business %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>
</div>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>






<div id="page-content">
    <div class="container">
        <ol class="breadcrumb">
            <li><%= link_to "Home", root_path %></li>
            <li class="active">Businesses</li>
        </ol>
        <!--end breadcrumb-->
        <section class="page-title">
            <h1>Businesses</h1>
            <%= link_to 'Add A Business', new_business_path, class: 'btn btn-rounded shadow pull-right' %>
        </section>
        <!--end page-title-->
        <section>
            <div class="my-items table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Business</th>
                        <th>Featured</th>
                        <th>Contact</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Last Edited</th>
                    </tr>
                    </thead>
                    <tbody>
                      <% @businesses.each do |b| %>
                    <tr class="my-item">
                        <td>
                            <div class="image-wrapper">
                                <!-- <div class="circle" data-toggle="tooltip" data-placement="right" title="Top Listing"><i class="fa fa-thumbs-up"></i></div> -->
                                <a href="edit-listing.html" class="image">
                                    <div class="bg-transfer">
                                      <%= image_tag b.logo %>
                                    </div>
                                </a>
                            </div>
                            <div class="info">
                                <a href="detail.html"><h2><%= b.name %></h2></a>
                                <figure class="location"><%= b.location.address.split(',')[1] %></figure>
                                <figure class="label label-info"><%= b.category.name %></figure>
                                <!-- <div class="additional-info">
                                    <span><i class="fa fa-bed"></i>12</span>
                                    <span class="price-info">From <span class="price">$32</span><span class="appendix">/night</span></span>
                                </div> -->
                                <!--end additional-info-->
                            </div>
                            <!--end info-->
                        </td>
                        <td><div class="featured yes"><i class="fa fa-check"></i><aside></aside></div></td>
                        <td class="views"><%= b.contact_name %></td>
                        <td class="reviews"><%= number_to_phone(b.contact_phone) %></td>
                        <td class="rating">
                          <%= link_to b.email, b.email %>
                           <!--  <div class="rating-passive" data-rating="4">
                                <span class="stars"></span>
                                <span class="reviews">6</span>
                            </div> -->
                        </td>
                        <td class="last-edited"><%= link_to b.website, b.website, :target => '_blank' %>
                            <!-- <span class="last-edit">Last edited: Today 12:35</span> -->
                            <div class="edit-options">
                                <%= link_to business_path(b), class: 'link icon' do %>
                                  <i class="fa fa-eye"></i>View
                                <% end %>
                                <%= link_to edit_business_path(b), class: 'link icon' do %>
                                  <i class="fa fa-edit"></i>Edit
                                <% end %>
                                <%= link_to  business_path(b), method: :delete, data: { confirm: 'Are you sure?' }, class: 'link icon delete' do %>
                                  <i class="fa fa-trash"></i>Delete</a>
                                <% end %>
                            </div>
                            <!--end edit-options-->
                        </td>
                    </tr>
                    <% end %>
                    </tbody>
                </table>
            </div>
            <!--end my-items-->
        </section>
        <section>
            <div class="center">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li class="disabled previous">
                            <a href="#" aria-label="Previous">
                                <i class="arrow_left"></i>
                            </a>
                        </li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li class="active"><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li class="next">
                            <a href="#" aria-label="Next">
                                <i class="arrow_right"></i>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </section>
    </div>
    <!--end container-->
</div>

app/views/businesses/new.html.erb
<h1>New Business</h1>
<%= link_to "<i class='fa fa-arrow-left'></i> Back".html_safe, businesses_path %>
<div class='row'>
  <div class='col-md-2'></div>
  <div class='col-md-8'>
    <%= render 'form', business: @business %>
  </div>
  <div class='col-md-2'></div>
</div>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>
<div id="page-content">
    <div class="container">
        <ol class="breadcrumb">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Businesses", businesses_path %></li>
            <li class="active">Details</li>
        </ol>

        <div class="row">
            <div class="col-md-9 col-sm-9">
                <section class="page-title">
                    <div class="pull-left">
                        <h1><%= @business.name %></h1>
                        <h3><%= @business.location.address %></h3>
                        <%= link_to 'Edit', edit_business_path(@business) %> |
                        <%= link_to 'Back', businesses_path %>
                       <!--  <div class="rating-passive" data-rating="4">
                            <span class="stars"></span>
                            <span class="reviews">6</span>
                        </div> -->
                    </div>
                    <!--end page-title-->
                    <!-- <a href="#write-a-review" class="btn btn-primary btn-framed btn-rounded btn-light-frame icon scroll pull-right"><i class="fa fa-star"></i>Write a review</a> -->
                </section>

                <div class="row">
                    <div class="col-md-8 col-sm-12">
                        <section>
                            <div class="gallery detail">
                                <div class="owl-carousel" data-owl-nav="0" data-owl-dots="1">
                                    <div class="image">
                                        <div class="bg-transfer"><img src="<%= @business.logo%>" alt=""></div>
                                    </div>
                                </div>
                                <!--end owl-carousel-->
                            </div>
                            <!--end gallery-->
                        </section>

                        <section>
                            <section>
                                <h2>Details </h2>
                                <p>
                                    <%= @business.description %>
                                </p>
                            </section>
                        </section>
<!--
                        <section class="box">
                            <h2>Opening Hours</h2>
                            <dl>
                                <dt>Monday</dt>
                                <dd>08:00am - 11:00pm</dd>
                                <dt>Tuesday</dt>
                                <dd>08:00am - 11:00pm</dd>
                                <dt>Wednesday</dt>
                                <dd>12:00am - 11:00pm</dd>
                                <dt>Thursday</dt>
                                <dd>08:00am - 11:00pm</dd>
                                <dt>Friday</dt>
                                <dd>03:00pm - 02:00am</dd>
                                <dt>Saturday</dt>
                                <dd>03:00pm - 02:00am</dd>
                                <dt>Sunday</dt>
                                <dd>Closed</dd>
                            </dl>
                        </section> -->

                       <!--  <section>
                            <h2>Reviews</h2>
                            <div class="review">
                                <div class="image">
                                    <div class="bg-transfer"><img src="assets/img/person-02.jpg" alt=""></div>
                                </div>
                                <div class="description">
                                    <figure>
                                        <div class="rating-passive" data-rating="4">
                                            <span class="stars"></span>
                                            <span class="reviews">6</span>
                                        </div>
                                        <span class="date">09.05.2016</span>
                                    </figure>
                                    <p>Donec nec tristique sapien. Aliquam ante felis, sagittis sodales diam sollicitudin, dapibus semper turpis</p>
                                </div>
                            </div>

                            <div class="review">
                                <div class="image">
                                    <div class="bg-transfer"><img src="assets/img/person-01.jpg" alt=""></div>
                                </div>
                                <div class="description">
                                    <figure>
                                        <div class="rating-passive" data-rating="5">
                                            <span class="stars"></span>
                                            <span class="reviews">6</span>
                                        </div>
                                        <span class="date">09.05.2016</span>
                                    </figure>
                                    <p>Vestibulum vel est massa. Integer pellentesque non augue et accumsan. Maecenas molestie elit nibh,
                                        vel vestibulum leo condimentum quis. Duis ac orci a magna auctor vehicula.
                                    </p>
                                </div>
                            </div>

                        </section> -->

                        <!-- <section id="write-a-review">
                            <h2>Write a Review</h2>
                            <form class="clearfix form inputs-underline">
                                <div class="box">
                                    <div class="comment">
                                        <div class="row">
                                            <div class="col-md-7">
                                                <div class="comment-title">
                                                    <h4>Review your experience</h4>
                                                </div>

                                                <div class="form-group">
                                                    <label for="name">Title of your review<em>*</em></label>
                                                    <input type="text" class="form-control" id="name" name="name" placeholder="Beautiful place!" required="">
                                                </div>
                                                <div class="form-group">
                                                    <label for="message">Your Message<em>*</em></label>
                                                    <textarea class="form-control" id="message" rows="8" name="message" required="" placeholder="Describe your experience"></textarea>
                                                </div>

                                            </div>

                                            <div class="col-md-5">
                                                <div class="comment-title">
                                                    <h4>Rating</h4>
                                                </div>

                                                <dl class="visitor-rating">
                                                    <dt>Comfort</dt>
                                                    <dd class="star-rating active" data-name="comfort"></dd>
                                                    <dt>Location</dt>
                                                    <dd class="star-rating active" data-name="location"></dd>
                                                    <dt>Facilities</dt>
                                                    <dd class="star-rating active" data-name="facilities"></dd>
                                                    <dt>Staff</dt>
                                                    <dd class="star-rating active" data-name="staff"></dd>
                                                    <dt>Value for money</dt>
                                                    <dd class="star-rating active" data-name="value"></dd>
                                                </dl>
                                            </div>

                                        </div>

                                        <br>
                                        <div class="form-group pull-right">
                                            <button type="submit" class="btn btn-primary btn-rounded">Send Review</button>
                                        </div>

                                    </div>

                                </div>

                            </form>
                        </section> -->
                    </div>
                    <!--end col-md-6-->
                    <div class="col-md-4 col-sm-12">
                        <section>
                            <div class="detail-sidebar">
                                <section class="shadow">
                                    <div class="map height-250px" id="map-detail"></div>
                                    <!--end map-->
                                    <div class="content">
                                        <div class="vertical-aligned-elements">
                                            <div class="element"><img src="assets/img/logo-2.png" alt=""></div>
                                            <div class="element text-align-right"><a href="#" class="btn btn-primary btn-rounded btn-xs">Claim</a></div>
                                        </div>
                                        <hr>
                                        <address>
                                            <figure><i class="fa fa-map-marker"></i><%= @business.location.address.split(',')[0] %><br> <%= @business.location.address.split(',')[1] %></figure>
                                            <figure><i class="fa fa-envelope"></i><a href="mailto:<%= @business.email %>"> <%= @business.email %></a></figure>
                                            <figure><i class="fa fa-phone"></i><%=  number_to_phone(@business.contact_phone) %></figure>
                                            <figure>
                                              <i class="fa fa-globe"></i>
                                              <a href="http://<%= @business.website %>" target='_blank'>website</a>
                                            </figure>
                                        </address>
                                    </div>
                                </section>
                            </div>
                            <!--end detail-sidebar-->
                        </section>
                        <section>
                            <h2>Categories</h2>
                            <ul class="tags">
                               <li><%= @business.category.name %></li>
                            </ul>
                        </section>
                    </div>
                    <!--end col-md-3-->
                </div>
                <!--end row-->
            </div>
            <!--end col-md-9-->

            <div class="col-md-3 col-sm-3">
                <aside class="sidebar">
                    <%= render 'businesses/partials/recent_items' %>
                </aside>
                <!--end sidebar-->
            </div>
            <!--end col-md-3-->
        </div>
    </div>
    <!--end container-->
</div>


<%= content_for :js do %>
<script>
    rating(".visitor-rating");
    var _latitude = <%= @business.location.latitude%>;
    var _longitude = <%= @business.location.longitude%>;
    var element = "map-detail";
    simpleMap(_latitude,_longitude, element);
</script>
<% end %>