config/routes.rb
Rails.application.routes.draw do
  resources :business_settings do
    get 'activate_ride_requests', to: 'business_settings#activate_ride_requests', as: 'activate_ride_requests'
    get 'deactivate_ride_requests', to: 'business_settings#deactivate_ride_requests', as: 'deactivate_ride_requests'
    get 'on_off_tracker', to: 'business_settings#on_off_tracker', as: 'on_off_tracker'
  end
  resources :kill_switches
  devise_for :users do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'ride_requests/inactive', to:'ride_requests#inactive', as: 'inactive'
  get 'ride_requests/new_2', to:'ride_requests#new_2', as: 'new_2'

  resources :ride_requests do
    get '/assign/:shuttle_id', to: 'ride_requests#assign_to_shuttle', as: 'assign_shuttle'
    get '/mark_clear', to: 'ride_requests#mark_clear', as: 'mark_clear'
    get 'advance_status', to:'ride_requests#advance_status', as: 'advance_status'
    get 'reset_status', to:'ride_requests#reset_status', as: 'reset_status'
    get 'send_inital_sms', to: 'ride_requests#send_inital_sms', as: 'send_inital_sms'
    get :autocomplete_pickup_location_name, :on => :collection

  end
  get 'ride_request/manager', to: "ride_requests#manager", as:'ride_request_manager'
  get 'ride_request/report', to: "ride_requests#report", as:'ride_request_report'
  get 'ride_request/show_all', to: "ride_requests#show_all", as:'ride_requests_show_all'
  get 'ride_request/check_last_ride/:id', to: "ride_requests#check_last_ride", as:'last_ride'
  resources :shuttle_stops
  resources :shuttles do
    get 'set_looping', to: 'shuttles#set_looping', as:'set_looping'
    get 'stop_looping', to: 'shuttles#stop_looping', as:'stop_looping'
    get 'set_active', to: 'shuttles#set_active', as:'set_active'
    get 'set_inactive', to: 'shuttles#set_inactive', as:'set_inactive'
    get 'driver', to: "shuttles#driver", as: "driver"
    get 'clear_all', to: "shuttles#clear_all", as: "clear_all"
    get 'all_rolling', to: "shuttles#all_rolling", as: "all_rolling"
    get 'check_last_ride/:id', to: 'shuttles#check_last_ride', as: 'check_last_ride'
    get 'check_hash/:hash', to: 'shuttles#check_hash', as: 'check_driver_hash'
  end
  get 'shuttle_locations', to: 'shuttles#shuttle_locations', as: 'shuttle_locations'
  get 'shuttle/trackers', to: 'shuttles#trackers', as: 'shuttle_trackers'
  get 'driver', to:'shuttles#driver', as: 'driver'
  get 'driver/:id', to:'shuttles#driver', as: 'driver_id'
  post 'driver/:id/set_location', to:'shuttles#set_location', as: 'set_location'
  post 'ride_requests/rider/set_location', to:'ride_requests#set_rider_location', as: 'set_rider_location'
  post 'ride_requests/rider/set_rider_info', to:'ride_requests#set_rider_info', as: 'set_rider_info'
  get 'ride_requests/rider/clear_session', to: 'ride_requests#clear_rider_info', as: 'clear_rider_info'
  get 'assign_drivers', to: 'shuttles#assign_drivers', as: 'assign_drivers'
  resources :images
  resources :experience_occurances do
    resources :reservations
  end
  resources :reservations do
    get 'deposit', to: 'reservations#deposit', as: 'deposit'
  end
  get 'my_reservations', to:'reservations#my_reservations', as: 'my_reservations'

  get 'experiences/featured', to: 'experiences#featured'
  resources :experiences do
    get 'add_company/:id', to: 'experiences#add_company', as: 'add_company'
    get 'remove_company/:id', to: 'experiences#remove_company', as: 'remove_company'
    resources :reservations
    resources :images
  end

  resources :experience_ideas
  resources :businesses
  resources :locations do
    get 'show_after_2', to: 'locations#set_show_after_2', as: 'show_after_2'
    get 'toggle_shuttle_stop', to: 'locations#toggle_shuttle_stop', as: 'toggle_shuttle_stop'
  end
  resources :categories

  resources :charges
  get 'set_play_sound', to: "business_settings#set_play_sound", as: 'set_play_sound'

  get 'test_text', to: 'twilios#send_test', as: 'twilio_test'

  get 'right_column_list', to: 'pages#right_column_list', as: 'right_column_list'
  get 'front_desk', to: 'pages#front_desk', as: 'front_desk'
  post 'pages/front_desk/send_sms', to: 'pages#send_sms', as: 'pages_send_sms'
  post 'pages/front_desk/send_sms_intl', to: 'pages#send_sms_intl', as: 'pages_send_sms_intl'
  get 'message_sent', to: 'pages#text_message_sent', as: 'text_message_sent'

  get 'mobile_pages/ride_request', to: 'mobile_pages#ride_request', as: 'mobile_ride_request'
  post 'mobile_pages/create', to: 'mobile_pages#create', as: 'mobile_create_ride_request'
  get 'mobile_pages/ride_request_details/:ride_request_id', to: 'mobile_pages#ride_request_details', as: 'mobile_ride_request_details'
  root "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/rlc/_categories_menu.html.erb
<ul>
  <% Category.all.each do |cat|%>
    <li class=""><a href="#nav-grid-listing"><%= cat.name %></a>
    </li>
  <% end %>
</ul>

app/views/shared/rlc/_header.html.erb
    <header id="page-header">
        <nav>
            <div class="left">

                <%= link_to "Resort Lodging Company Extras",  "http://resortlodgingcompany.com" %>
            </div>
            <!--end left-->
            <div class="right">
                <div class="primary-nav has-mega-menu">
                    <ul class="navigation">
                        <li><%= link_to "Experiences", experiences_path %></li>
                        <% if current_user %>
                            <li><%= link_to "Shuttles", ride_request_manager_path %></li>
                            <li><%= link_to "Locations", locations_path %></li>
                        <% else %>
                            <li><%= link_to "New Ride", new_ride_request_path %></li>
                        <% end %>
                        <%= render 'shared/rlc/menu_items/devise' %>
                    </ul>
                    <!--end navigation-->
                </div>
                <!--end primary-nav-->
                <!-- <div class="secondary-nav">
                    <a href="#" data-modal-external-file="modal_sign_in.php" data-target="modal-sign-in">Sign In</a>
                    <a href="#" class="promoted" data-modal-external-file="modal_register.php" data-target="modal-register">Register</a>
                </div> -->
                <!--end secondary-nav-->
                <!-- <a href="#" class="btn btn-primary btn-small btn-rounded icon shadow add-listing" data-modal-external-file="modal_submit.php" data-target="modal-submit"><i class="fa fa-plus"></i><span>Add listing</span></a> -->
                <div class="nav-btn">
                    <i></i>
                    <i></i>
                    <i></i>
                </div>
                <!--end nav-btn-->
            </div>
            <!--end right-->
        </nav>
        <!--end nav-->
    </header>
    <!--end page-header-->

app/views/shared/rlc/_hero.html.erb
<div class="hero-section has-background full-screen background-is-dark">
  <div class="form search-form horizontal position-bottom">
    <div class="container">
      <form>
        <div class="row">
          <div class="col-md-3 col-sm-2">
            <div class="form-group">
              <input type="text" class="form-control" name="keyword" placeholder="Enter keyword">
            </div>
            <!--end form-group-->
          </div>
          <!--end col-md-4-->
          <div class="col-md-3 col-sm-4">
            <div class="form-group">
              <select class="form-control selectpicker" name="location">
                <option value="">Location</option>
                <option value="1">New York</option>
                <option value="2">Washington</option>
                <option value="3">London</option>
                <option value="4">Paris</option>
              </select>
            </div>
            <!--end form-group-->
          </div>
          <!--end col-md-4-->
          <div class="col-md-3 col-sm-4">
            <div class="form-group">
              <select class="form-control selectpicker" name="category">
                <option value="">Category</option>
                <option value="1">Restaurant</option>
                <option value="2">Event</option>
                <option value="3">Adrenaline</option>
                <option value="4">Sport</option>
                <option value="5">Wellness</option>
              </select>
            </div>
            <!--end form-group-->
          </div>
          <!--end col-md-4-->
          <div class="col-md-2 col-sm-4">
         <!--  <div class="form-group">
              <input type="text" class="form-control date-picker"  placeholder="Event Date">
            </div> -->
            <!--end form-group-->
          </div>
          <!--end col-md-4-->
          <div class="col-md-1 col-sm-4">
            <div class="form-group">
              <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-search"></i></button>
            </div>
            <!--end form-group-->
          </div>
          <!--end col-md-4-->
        </div>
        <!--end row-->
      </form>
      <!--end form-hero-->
    </div>
    <!--end container-->
  </div>
  <!--end search-form-->

  <div class="slider">
    <div class="owl-carousel" data-owl-nav="0" data-owl-dots="1" data-owl-loop="1">
      <% @header_experiences.each do |he|%>
      <div class="slide">
        <div class="presentation">
          <div class="description">
            <div class="container">
              <h1><%= he.title %></h1>
              <h2>Pickup: <i class="fa fa-map-marker"></i>Your Hotel</h2>
              <div class="rating-passive" data-rating="4">
                <span class="stars"></span>
                <span class="reviews">6</span>
              </div>
              <div class="label label-default"><%= he.categories.first.name %></div>
              <hr>
              <%= link_to "View Detail", he, class: 'btn btn-default btn-framed btn-rounded' %>
            </div>
          </div>
          <div class="image">
            <div class="bg-transfer">
              <% if he.header_image %>
                <%= image_tag he.header_image %>
              <% else %>
                <%= image_tag he.images.first.file %>
              <% end %>

            </div>
          </div>
        </div>
        <!--end presentation-->
      </div>
      <% end %>
    </div>
    <!--end owl-carousel-->
  </div>
  <!--end slider-->
</div>
<!--end hero-section-->

app/views/shared/rlc/_recent_experiences.html.erb
 <section class="block">
            <div class="container">
                <div class="center">
                    <div class="section-title">
                        <div class="center">
                            <h2>Recent Experiences</h2>
                            <h3 class="subtitle">The Most Fun You Can Hace Off The Mountain</h3>
                        </div>
                    </div>
                    <!--end section-title-->
                </div>
                <!--end center-->
                <div class="row">
                    <div class="col-md-3 col-sm-3">
                        <div class="item" data-id="1">
                            <figure class="circle featured sale">$50</figure>
                            <a href="/experiences/1">
                                <div class="description">
                                    <!-- <figure>From: $80</figure> -->
                                    <div class="label label-default">Foodie</div>
                                    <h3>To All A Goodnight</h3>
                                    <h4>2 Hours </h4>
                                </div>
                                <!--end description-->
                                <div class="image bg-transfer">
                                    <img src="assets/img/items/1.jpg" alt="">
                                </div>
                                <!--end image-->
                            </a>
                            <div class="additional-info">
                                <div class="rating-passive" data-rating="4">
                                    <span class="stars"></span>
                                    <span class="reviews">6</span>
                                </div>
                                <div class="controls-more">
                                    <ul>
                                        <li><a href="#">Add to favorites</a></li>
                                        <li><a href="#">Add to watchlist</a></li>
                                        <li><a href="#" class="quick-detail">Quick detail</a></li>
                                    </ul>
                                </div>
                                <!--end controls-more-->
                            </div>
                            <!--end additional-info-->
                        </div>
                        <!--end item-->
                    </div>
                    <!--<end col-md-3-->
                    <div class="col-md-3 col-sm-3">
                        <div class="item" data-id="2">
                            <figure class="circle featured sale">-50%</figure>
                            <a href="detail.html">
                                <div class="description">
                                    <figure>From: $40</figure>
                                    <div class="label label-default">Restaurant</div>
                                    <h3>Ironapple</h3>
                                    <h4>4209 Glenview Drive</h4>
                                </div>
                                <!--end description-->
                                <div class="image bg-transfer">
                                    <img src="assets/img/items/2.jpg" alt="">
                                </div>
                                <!--end image-->
                            </a>
                            <div class="additional-info">
                                <div class="rating-passive" data-rating="3">
                                    <span class="stars"></span>
                                    <span class="reviews">13</span>
                                </div>
                                <div class="controls-more">
                                    <ul>
                                        <li><a href="#">Add to favorites</a></li>
                                        <li><a href="#">Add to watchlist</a></li>
                                        <li><a href="#" class="quick-detail">Quick detail</a></li>
                                    </ul>
                                </div>
                                <!--end controls-more-->
                            </div>
                            <!--end additional-info-->
                        </div>
                        <!--end item-->
                    </div>
                    <!--<end col-md-3-->
                    <div class="col-md-6 col-sm-6">
                        <div class="item" data-id="15">
                            <figure class="circle featured sale">-15%</figure>
                            <figure class="ribbon">Top</figure>
                            <a href="detail.html">
                                <div class="description">
                                    <figure>From: $30</figure>
                                    <div class="label label-default">Bar & Grill</div>
                                    <h3>Bambi Planet Houseboat Bar& Grill </h3>
                                    <h4>3857 Losh Lane</h4>
                                </div>
                                <!--end description-->
                                <div class="image bg-transfer">
                                    <img src="assets/img/items/3.jpg" alt="">
                                </div>
                                <!--end image-->
                            </a>
                            <div class="additional-info">
                                <figure class="circle" title="Featured"><i class="fa fa-check"></i></figure>
                                <div class="rating-passive" data-rating="5">
                                    <span class="stars"></span>
                                    <span class="reviews">56</span>
                                </div>
                                <div class="controls-more">
                                    <ul>
                                        <li><a href="#">Add to favorites</a></li>
                                        <li><a href="#">Add to watchlist</a></li>
                                        <li><a href="#" class="quick-detail">Quick detail</a></li>
                                    </ul>
                                </div>
                                <!--end controls-more-->
                            </div>
                            <!--end additional-info-->
                        </div>
                        <!--end item-->
                    </div>
                    <!--<end col-md-3-->
                    <div class="col-md-4 col-sm-4">
                        <div class="item" data-id="3">
                            <figure class="circle featured sale">-43%</figure>
                            <figure class="ribbon">Top</figure>
                            <a href="detail.html">
                                <div class="description">
                                    <figure>From: $67</figure>
                                    <div class="label label-default">Event</div>
                                    <h3>Food Festival</h3>
                                    <h4>840 My Drive</h4>
                                </div>
                                <!--end description-->
                                <div class="image bg-transfer">
                                    <img src="assets/img/items/4.jpg" alt="">
                                </div>
                                <!--end image-->
                            </a>
                            <div class="additional-info">
                                <figure class="circle" title="Featured"><i class="fa fa-check"></i></figure>
                                <div class="rating-passive" data-rating="5">
                                    <span class="stars"></span>
                                    <span class="reviews">12</span>
                                </div>
                                <div class="controls-more">
                                    <ul>
                                        <li><a href="#">Add to favorites</a></li>
                                        <li><a href="#">Add to watchlist</a></li>
                                        <li><a href="#" class="quick-detail">Quick detail</a></li>
                                    </ul>
                                </div>
                                <!--end controls-more-->
                            </div>
                            <!--end additional-info-->
                        </div>
                        <!--end item-->
                    </div>
                    <!--<end col-md-4-->
                    <div class="col-md-3 col-sm-3">
                        <div class="item" data-id="4">
                            <figure class="circle featured sale">-28%</figure>
                            <a href="detail.html">
                                <div class="description">
                                    <figure>From: $29</figure>
                                    <div class="label label-default">Lounge</div>
                                    <h3>Cosmopolit</h3>
                                    <h4>2896 Ripple Street</h4>
                                </div>
                                <!--end description-->
                                <div class="image bg-transfer">
                                    <img src="assets/img/items/5.jpg" alt="">
                                </div>
                                <!--end image-->
                            </a>
                            <div class="additional-info">
                                <div class="rating-passive" data-rating="5">
                                    <span class="stars"></span>
                                    <span class="reviews">43</span>
                                </div>
                                <div class="controls-more">
                                    <ul>
                                        <li><a href="#">Add to favorites</a></li>
                                        <li><a href="#">Add to watchlist</a></li>
                                        <li><a href="#" class="quick-detail">Quick detail</a></li>
                                    </ul>
                                </div>
                                <!--end controls-more-->
                            </div>
                            <!--end additional-info-->
                        </div>
                        <!--end item-->
                    </div>
                    <!--<end col-md-3-->
                    <div class="col-md-5 col-sm-5">
                        <div class="item" data-id="6">
                            <figure class="circle featured sale">-45%</figure>
                            <a href="detail.html">
                                <div class="description">
                                    <figure>Free entry</figure>
                                    <div class="label label-default">Concert</div>
                                    <h3>Stand Up Show</h3>
                                    <h4>371 Kinney Street</h4>
                                </div>
                                <!--end description-->
                                <div class="image bg-transfer">
                                    <img src="assets/img/items/6.jpg" alt="">
                                </div>
                                <!--end image-->
                            </a>
                            <div class="additional-info">
                                <div class="rating-passive" data-rating="0">
                                    <span class="stars"></span>
                                    <span class="reviews">0</span>
                                </div>
                                <div class="controls-more">
                                    <ul>
                                        <li><a href="#">Add to favorites</a></li>
                                        <li><a href="#">Add to watchlist</a></li>
                                        <li><a href="#" class="quick-detail">Quick detail</a></li>
                                    </ul>
                                </div>
                                <!--end controls-more-->
                            </div>
                            <!--end additional-info-->
                        </div>
                        <!--end item-->
                    </div>
                    <!--<end col-md-3-->
                </div>
                <!--end row-->
                <div class="center">
                    <a href="listing.html" class="btn btn-primary btn-light-frame btn-rounded btn-framed arrow">View all listings</a>
                </div>
            <!--end center-->
            </div>
            <!--end container-->
        </section>