config/routes.rb
Rails.application.routes.draw do
  resources :business_settings do
    get 'activate_ride_requests', to: 'business_settings#activate_ride_requests', as: 'activate_ride_requests'
    get 'deactivate_ride_requests', to: 'business_settings#deactivate_ride_requests', as: 'deactivate_ride_requests'
    get 'on_off_tracker', to: 'business_settings#on_off_tracker', as: 'on_off_tracker'
  end
  resources :kill_switches
  devise_for :users do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'ride_requests/inactive', to:'ride_requests#inactive', as: 'inactive'
  get 'ride_requests/new_2', to:'ride_requests#new_2', as: 'new_2'

  resources :ride_requests do
    get '/assign/:shuttle_id', to: 'ride_requests#assign_to_shuttle', as: 'assign_shuttle'
    get '/mark_clear', to: 'ride_requests#mark_clear', as: 'mark_clear'
    get 'advance_status', to:'ride_requests#advance_status', as: 'advance_status'
    get 'reset_status', to:'ride_requests#reset_status', as: 'reset_status'
    get 'send_inital_sms', to: 'ride_requests#send_inital_sms', as: 'send_inital_sms'
    get :autocomplete_pickup_location_name, :on => :collection

  end
  get 'ride_request/manager', to: "ride_requests#manager", as:'ride_request_manager'
  get 'ride_request/report', to: "ride_requests#report", as:'ride_request_report'
  get 'ride_request/show_all', to: "ride_requests#show_all", as:'ride_requests_show_all'
  get 'ride_request/check_last_ride/:id', to: "ride_requests#check_last_ride", as:'last_ride'
  resources :shuttle_stops
  resources :shuttles do
    get 'set_looping', to: 'shuttles#set_looping', as:'set_looping'
    get 'stop_looping', to: 'shuttles#stop_looping', as:'stop_looping'
    get 'set_active', to: 'shuttles#set_active', as:'set_active'
    get 'set_inactive', to: 'shuttles#set_inactive', as:'set_inactive'
    get 'driver', to: "shuttles#driver", as: "driver"
    get 'clear_all', to: "shuttles#clear_all", as: "clear_all"
    get 'all_rolling', to: "shuttles#all_rolling", as: "all_rolling"
    get 'check_last_ride/:id', to: 'shuttles#check_last_ride', as: 'check_last_ride'
    get 'check_hash/:hash', to: 'shuttles#check_hash', as: 'check_driver_hash'
  end
  get 'shuttle_locations', to: 'shuttles#shuttle_locations', as: 'shuttle_locations'
  get 'shuttle/trackers', to: 'shuttles#trackers', as: 'shuttle_trackers'
  get 'driver', to:'shuttles#driver', as: 'driver'
  get 'driver/:id', to:'shuttles#driver', as: 'driver_id'
  post 'driver/:id/set_location', to:'shuttles#set_location', as: 'set_location'
  post 'ride_requests/rider/set_location', to:'ride_requests#set_rider_location', as: 'set_rider_location'
  post 'ride_requests/rider/set_rider_info', to:'ride_requests#set_rider_info', as: 'set_rider_info'
  get 'ride_requests/rider/clear_session', to: 'ride_requests#clear_rider_info', as: 'clear_rider_info'
  get 'assign_drivers', to: 'shuttles#assign_drivers', as: 'assign_drivers'
  resources :images
  resources :experience_occurances do
    resources :reservations
  end
  resources :reservations do
    get 'deposit', to: 'reservations#deposit', as: 'deposit'
  end
  get 'my_reservations', to:'reservations#my_reservations', as: 'my_reservations'

  get 'experiences/featured', to: 'experiences#featured'
  resources :experiences do
    get 'add_company/:id', to: 'experiences#add_company', as: 'add_company'
    get 'remove_company/:id', to: 'experiences#remove_company', as: 'remove_company'
    resources :reservations
    resources :images
  end

  resources :experience_ideas
  resources :businesses
  resources :locations do
    get 'show_after_2', to: 'locations#set_show_after_2', as: 'show_after_2'
    get 'toggle_shuttle_stop', to: 'locations#toggle_shuttle_stop', as: 'toggle_shuttle_stop'
  end
  resources :categories

  resources :charges
  get 'set_play_sound', to: "business_settings#set_play_sound", as: 'set_play_sound'

  get 'test_text', to: 'twilios#send_test', as: 'twilio_test'

  get 'right_column_list', to: 'pages#right_column_list', as: 'right_column_list'
  get 'front_desk', to: 'pages#front_desk', as: 'front_desk'
  post 'pages/front_desk/send_sms', to: 'pages#send_sms', as: 'pages_send_sms'
  post 'pages/front_desk/send_sms_intl', to: 'pages#send_sms_intl', as: 'pages_send_sms_intl'
  get 'message_sent', to: 'pages#text_message_sent', as: 'text_message_sent'

  get 'mobile_pages/ride_request', to: 'mobile_pages#ride_request', as: 'mobile_ride_request'
  post 'mobile_pages/create', to: 'mobile_pages#create', as: 'mobile_create_ride_request'
  get 'mobile_pages/ride_request_details/:ride_request_id', to: 'mobile_pages#ride_request_details', as: 'mobile_ride_request_details'
  root "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/business_setting.rb
class BusinessSetting < ApplicationRecord
end

app/controllers/business_settings_controller.rb
class BusinessSettingsController < ApplicationController
  before_action :set_business_setting, only: [:show, :edit, :update, :destroy, :activate_ride_requests, :deactivate_ride_requests]
  layout 'locations_2'
  # GET /business_settings
  # GET /business_settings.json
  def index
    @business_settings = BusinessSetting.all
  end

  # GET /business_settings/1
  # GET /business_settings/1.json
  def show
  end

  # GET /business_settings/new
  def new
    @business_setting = BusinessSetting.new
  end

  # GET /business_settings/1/edit
  def edit
  end

  # POST /business_settings
  # POST /business_settings.json
  def create
    @business_setting = BusinessSetting.new(business_setting_params)

    respond_to do |format|
      if @business_setting.save
        format.html { redirect_to @business_setting, notice: 'Business setting was successfully created.' }
        format.json { render :show, status: :created, location: @business_setting }
      else
        format.html { render :new }
        format.json { render json: @business_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_settings/1
  # PATCH/PUT /business_settings/1.json
  def update
    respond_to do |format|
      if @business_setting.update(business_setting_params)
        format.html { redirect_to @business_setting, notice: 'Business setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_setting }
      else
        format.html { render :edit }
        format.json { render json: @business_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_settings/1
  # DELETE /business_settings/1.json
  def destroy
    @business_setting.destroy
    respond_to do |format|
      format.html { redirect_to business_settings_url, notice: 'Business setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate_ride_requests
    @business_setting.ride_request_active = true
    @business_setting.save
    OnOffTracker.create!(status: "active")
    redirect_to ride_request_manager_path
  end

  def deactivate_ride_requests
    @business_setting.ride_request_active = false
    @business_setting.save
    OnOffTracker.create!(status: "inactive")
    redirect_to ride_request_manager_path
  end

  def set_play_sound
    bs = BusinessSetting.first
    if bs.play_sound == true
      bs.play_sound = false;
      bs.save
    else
      bs.play_sound = true
      bs.save
    end
    redirect_to ride_request_manager_path
  end

  def on_off_tracker
    @trackers = OnOffTracker.all.reverse
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_setting
      if params[:business_setting_id]
         @business_setting = BusinessSetting.find(params[:business_setting_id])
       else
        @business_setting = BusinessSetting.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_setting_params
      params.require(:business_setting).permit(:ride_request_active, :title)
    end
end

app/helpers/business_settings_helper.rb
module BusinessSettingsHelper
end

app/views/business_settings/_form.html.erb
<%= form_with(model: business_setting, local: true) do |form| %>
  <% if business_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business_setting.errors.count, "error") %> prohibited this business_setting from being saved:</h2>

      <ul>
      <% business_setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ride_request_active %>
    <%= form.check_box :ride_request_active, id: :business_setting_ride_request_active %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :business_setting_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/business_settings/edit.html.erb
<h1>Editing Business Setting</h1>

<%= render 'form', business_setting: @business_setting %>

<%= link_to 'Show', @business_setting %> |
<%= link_to 'Back', business_settings_path %>

app/views/business_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Business Settings</h1>

<table>
  <thead>
    <tr>
      <th>Ride request active</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_settings.each do |business_setting| %>
      <tr>
        <td><%= business_setting.ride_request_active %></td>
        <td><%= business_setting.title %></td>
        <td><%= link_to 'Show', business_setting %></td>
        <td><%= link_to 'Edit', edit_business_setting_path(business_setting) %></td>
        <td><%= link_to 'Destroy', business_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business Setting', new_business_setting_path %>

app/views/business_settings/new.html.erb
<h1>New Business Setting</h1>

<%= render 'form', business_setting: @business_setting %>

<%= link_to 'Back', business_settings_path %>

app/views/business_settings/on_off_tracker.html.erb
<div class='container'>
  <h1> System On / Off Tracking </h1>
<% @trackers.each do |t| %>
  <div class='row'>
    <% if t.status == "active" %>
      <i class='fa fa-power-off' style='color:green'></i>
    <% else %>
      <i class='fa fa-ban' style='color:red'></i>
    <% end %>

    <%= t.status %> - at <%= t.updated_at.strftime("%B %d, %Y: %H:%M %Z") %>
  </div>
<% end %>
</div>

app/views/business_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ride request active:</strong>
  <%= @business_setting.ride_request_active %>
</p>

<p>
  <strong>Title:</strong>
  <%= @business_setting.title %>
</p>

<%= link_to 'Edit', edit_business_setting_path(@business_setting) %> |
<%= link_to 'Back', business_settings_path %>